### PR TITLE
ens

### PR DESCRIPTION
**Pull request by ars0x**

### CODE REVIEW

**Comment by nykma** [comment]
Seems like you are plagiarizing #46 . If no further explanation is given, this PR will be closed.

**Comment by ars0x** [comment]
If not needed,Close this!

**Comment by ash0521** [comment]
https://github.com/NextDotID/proof_server/pull/71

**Comment by ash0521** [comment]
Add the slack platform support https://github.com/NextDotID/proof_server/pull/71

**Pull request closed without merging**
