### PR TITLE
Add the slack platform support

### PR DESCRIPTION
**Pull request by ars0x**

### CODE REVIEW

**Comment by ars0x** [comment]
?

**Comment by ars0x** [comment]
Please could you response me quickly?

**Comment by BinaryHB0916** [comment]
@nykma could you take a look by next Monday?

**Comment by nykma** [comment]
I'll take a look after this CI check is passed.

**Comment by ars0x** [comment]
Rewrite

**Comment by ars0x** [comment]
Why this error?

**Comment by ars0x** [comment]
shell script error

**Comment by ars0x** [comment]
Run again
go build config/main.go
./main

**Comment by ars0x** [comment]
Look at the first line of the shell script file
[ -f "config/main.go" ]

**Comment by nykma** [comment]
Your CI check is failed. It's not CI's fault.

**Comment by ars0x** [comment]
Reply me on telegram

**Comment by ars0x** [comment]
Reply me on telegram

**Comment by BinaryHB0916** [comment]
@ars0x Hi, Thanks for your contribution. 

Please communicate here to make this context visible to other community members.

**Pull request closed without merging**
